---
galaxy_info:
  author: Alen Stimec 
  description: Ansible playbook for deploying PowerBroker Identity Services PBIS Open Edition for RedHat/CentOS
  company: future.inc
  license: MIT
  min_ansible_version: 1.2

  platforms:
  - name: EL
    versions:
     - 6

  categories:
  - system

  
