---
# tasks file for pbis on Ubuntu
# repo info available: http://repo.pbis.beyondtrust.com/apt.html

   - name: add BeyondTrust PBIS open apt repo key
     apt_key: url=http://repo.pbis.beyondtrust.com/yum/RPM-GPG-KEY-pbis

   - name: add BeyondTrust PBIS open apt repo
     apt_repository: repo='deb http://repo.pbis.beyondtrust.com/apt pbiso main' state=present

   - name: apt-get update
     apt: update_cache=yes

   - name: apt-get install pbis-open
     apt: name=pbis-open state=latest
